import { Agent, AuditLogEntry } from '@/types/agent';

export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'DataAnalyzer',
    status: 'running',
    currentTool: 'database_query',
    permissions: [
      { tool: 'database_query', allowed: true, scope: 'read-write' },
      { tool: 'file_system', allowed: true, scope: 'read-write' },
      { tool: 'api_call', allowed: true, scope: 'all' },
      { tool: 'code_execution', allowed: true, scope: 'sandboxed' },
      { tool: 'email_send', allowed: true, scope: 'internal' },
    ],
  },
  {
    id: 'agent-002',
    name: 'CodeAssistant',
    status: 'idle',
    permissions: [
      { tool: 'database_query', allowed: true, scope: 'read-only' },
      { tool: 'file_system', allowed: true, scope: 'read-write' },
      { tool: 'api_call', allowed: true, scope: 'restricted' },
      { tool: 'code_execution', allowed: true, scope: 'sandboxed' },
      { tool: 'email_send', allowed: false },
    ],
  },
  {
    id: 'agent-003',
    name: 'SecurityAuditor',
    status: 'paused',
    permissions: [
      { tool: 'database_query', allowed: true, scope: 'read-only' },
      { tool: 'file_system', allowed: true, scope: 'read-only' },
      { tool: 'api_call', allowed: false },
      { tool: 'code_execution', allowed: false },
      { tool: 'email_send', allowed: false },
    ],
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000);
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000);

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: minutesAgo(2),
    agentId: 'agent-001',
    action: 'query_executed',
    tool: 'database_query',
    input: 'SELECT * FROM analytics WHERE date > NOW() - INTERVAL 7 DAY',
    output: 'Returned 1,234 rows in 142ms',
    success: true,
    duration: 142,
  },
  {
    id: 'log-002',
    timestamp: minutesAgo(5),
    agentId: 'agent-002',
    action: 'file_read',
    tool: 'file_system',
    input: '/workspace/src/utils/helpers.ts',
    output: 'File read successfully, 2.4KB',
    success: true,
    duration: 18,
  },
  {
    id: 'log-003',
    timestamp: minutesAgo(8),
    agentId: 'agent-001',
    action: 'api_request',
    tool: 'api_call',
    input: 'GET https://api.internal.example.com/metrics',
    output: '{"status":200,"data":{"cpu":45.2,"memory":72.1}}',
    success: true,
    duration: 234,
  },
  {
    id: 'log-004',
    timestamp: minutesAgo(12),
    agentId: 'agent-002',
    action: 'code_run',
    tool: 'code_execution',
    input: 'python analyze_data.py --input dataset.csv',
    output: 'Analysis complete. Output written to results.json',
    success: true,
    duration: 3210,
  },
  {
    id: 'log-005',
    timestamp: minutesAgo(15),
    agentId: 'agent-003',
    action: 'email_denied',
    tool: 'email_send',
    input: 'Send security report to admin@example.com',
    output: 'PERMISSION DENIED: email_send not allowed for SecurityAuditor',
    success: false,
    duration: 3,
  },
  {
    id: 'log-006',
    timestamp: minutesAgo(22),
    agentId: 'agent-001',
    action: 'query_executed',
    tool: 'database_query',
    input: 'UPDATE users SET last_login = NOW() WHERE id = 42',
    output: '1 row affected',
    success: true,
    duration: 89,
  },
  {
    id: 'log-007',
    timestamp: minutesAgo(30),
    agentId: 'agent-003',
    action: 'file_read',
    tool: 'file_system',
    input: '/var/log/audit/security.log',
    output: 'File read successfully, 18.7KB',
    success: true,
    duration: 41,
  },
  {
    id: 'log-008',
    timestamp: minutesAgo(35),
    agentId: 'agent-002',
    action: 'api_denied',
    tool: 'api_call',
    input: 'POST https://api.external.example.com/webhook',
    output: 'PERMISSION DENIED: api_call scope restricted to internal endpoints',
    success: false,
    duration: 2,
  },
  {
    id: 'log-009',
    timestamp: hoursAgo(1),
    agentId: 'agent-001',
    action: 'circuit_breaker_activated',
    tool: 'code_execution',
    input: 'Execute batch processing script - attempt 4/3',
    output: 'CIRCUIT BREAKER: Max retry limit exceeded. Agent paused for 60s.',
    success: false,
    duration: 5001,
  },
  {
    id: 'log-010',
    timestamp: hoursAgo(1.2),
    agentId: 'agent-001',
    action: 'code_run',
    tool: 'code_execution',
    input: 'node batch_processor.js --workers 4',
    output: 'Process terminated: timeout after 5000ms',
    success: false,
    duration: 5000,
  },
  {
    id: 'log-011',
    timestamp: hoursAgo(2),
    agentId: 'agent-002',
    action: 'file_write',
    tool: 'file_system',
    input: '/workspace/output/report_2024.md',
    output: 'File written successfully, 8.1KB',
    success: true,
    duration: 22,
  },
  {
    id: 'log-012',
    timestamp: hoursAgo(2.5),
    agentId: 'agent-003',
    action: 'query_executed',
    tool: 'database_query',
    input: 'SELECT user_id, action, timestamp FROM audit_log ORDER BY timestamp DESC LIMIT 100',
    output: 'Returned 100 rows in 67ms',
    success: true,
    duration: 67,
  },
  {
    id: 'log-013',
    timestamp: hoursAgo(3),
    agentId: 'agent-001',
    action: 'email_sent',
    tool: 'email_send',
    input: 'Send weekly analytics digest to team@example.com',
    output: 'Email delivered successfully. MessageId: msg-7839ab',
    success: true,
    duration: 450,
  },
  {
    id: 'log-014',
    timestamp: hoursAgo(4),
    agentId: 'agent-002',
    action: 'code_run',
    tool: 'code_execution',
    input: 'tsc --noEmit --strict',
    output: 'TypeScript compilation succeeded with 0 errors',
    success: true,
    duration: 1890,
  },
  {
    id: 'log-015',
    timestamp: hoursAgo(5),
    agentId: 'agent-003',
    action: 'api_denied',
    tool: 'api_call',
    input: 'GET https://external-service.io/data',
    output: 'PERMISSION DENIED: api_call not allowed for SecurityAuditor',
    success: false,
    duration: 2,
  },
  {
    id: 'log-016',
    timestamp: hoursAgo(8),
    agentId: 'agent-001',
    action: 'api_request',
    tool: 'api_call',
    input: 'POST https://api.internal.example.com/events',
    output: '{"status":201,"id":"evt-992"}',
    success: true,
    duration: 189,
  },
  {
    id: 'log-017',
    timestamp: hoursAgo(12),
    agentId: 'agent-002',
    action: 'file_read',
    tool: 'file_system',
    input: '/workspace/config/settings.json',
    output: 'File read successfully, 512B',
    success: true,
    duration: 9,
  },
  {
    id: 'log-018',
    timestamp: hoursAgo(16),
    agentId: 'agent-003',
    action: 'query_executed',
    tool: 'database_query',
    input: 'SELECT COUNT(*) FROM failed_logins WHERE timestamp > NOW() - INTERVAL 24 HOUR',
    output: 'Returned 1 row: {"count": 14}',
    success: true,
    duration: 55,
  },
  {
    id: 'log-019',
    timestamp: hoursAgo(20),
    agentId: 'agent-001',
    action: 'code_run',
    tool: 'code_execution',
    input: 'python ml_inference.py --model gpt-embeddings --input corpus.txt',
    output: 'Inference complete. Embeddings saved to vectors.npy (45.2MB)',
    success: true,
    duration: 12400,
  },
  {
    id: 'log-020',
    timestamp: hoursAgo(23),
    agentId: 'agent-002',
    action: 'api_request',
    tool: 'api_call',
    input: 'GET https://api.internal.example.com/health',
    output: '{"status":"healthy","version":"2.1.4","uptime":86340}',
    success: true,
    duration: 78,
  },
];

// Attach last action to agents
mockAgents[0].lastAction = mockAuditLogs[0];
mockAgents[1].lastAction = mockAuditLogs[1];
mockAgents[2].lastAction = mockAuditLogs[6];
